CREATE TABLE ACTIVE_DRIVERS (
    DRIVER_ID CHAR (5) PRIMARY KEY, 
    DRIVER_FIRST_NAME VARCHAR (20), 
    DRIVER_LAST_NAME VARCHAR (20),
    DRIVER_DRIVING_LICENSE_ID VARCHAR (10), 
    DRIVER_DRIVING_LICENSE_CHECKED BOOL, 
    DRIVER_RATING DECIMAL (2,1)
